name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        challenge: ["bootleg_crypto", "bootleg_crypto_again", "finches_in_a_pie", "finches_in_a_stack", "not_really_ai", "puffer_overflow", "really_simple_algorithm", "really_small_algorithm", "really_speedy_algorithm", "teleport", "access_0000", "collide", "emojasm_1", "emojasm_2", "pearlpearlpearl", "pybo", "quarantine", "raro"]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build challenge
      run: cd 2020/${{ matrix.challenge }} && docker build -t docker.pkg.github.com/ractf/challenges/${{ matrix.challenge }}:latest . && docker push docker.pkg.github.com/ractf/challenges/$${{ matrix.challenge }}:latest